In [1]:
import numpy as np
import torch
import clip
from transformers import AutoImageProcessor, AutoModel
from qdrant_client import QdrantClient, models
from pymilvus import MilvusClient, DataType
import pandas as pd
from PIL import Image
import os
import time
import random

os.getpid()

/home/inna/.cache/pypoetry/virtualenvs/sneakersearch-z_mDpiHd-py3.12/lib/python3.12/site-packages/clip/clip.py:6: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import packaging
/home/inna/.cache/pypoetry/virtualenvs/sneakersearch-z_mDpiHd-py3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

763905

In [2]:
#поднимаем ВБД с маппингом в корень прокта
# в корне проекта выполнить 

#docker run -p 6333:6333 -p 6334:6334 -v "$(pwd)/qdrant_storage:/qdrant/storage" qdrant/qdrant

# инициализация клиента ВБД
client = QdrantClient("http://localhost:6333")

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# client.recreate_collection(
#         collection_name="sneakers",
#         vectors_config=models.VectorParams(size=512, distance=models.Distance.COSINE),
#     )

/tmp/ipykernel_15972/1366355860.py:1: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  client.recreate_collection(

True

In [3]:
prefix_path = "/home/inna/Рабочий стол/SneakerSearch/data/"

lamoda_data = pd.read_csv(prefix_path+"lamoda_data.csv", sep=";")
lamoda_data

,brand,model,category,color,description,lamoda_photo,title_photo,path_to_lamoda_photo
0,Kappa,Kappa Кроссовки SIERRA MESH,Кроссовки,67545,NaN,https://a.lmcdn.ru/product/M/P/MP002XW12WY2_26...,lamoda_photos/Kappa_Kappa_Кроссовки_SIERRA_MES...,//a.lmcdn.ru/product/M/P/MP002XW12WY2_26197854...
1,Kappa,Kappa Кроссовки SIERRA MESH,Кроссовки,67545,NaN,https://a.lmcdn.ru/product/M/P/MP002XW12WY2_26...,lamoda_photos/Kappa_Kappa_Кроссовки_SIERRA_MES...,//a.lmcdn.ru/product/M/P/MP002XW12WY2_26197854...
2,Kappa,Kappa Кроссовки SIERRA MESH,Кроссовки,67545,NaN,https://a.lmcdn.ru/product/M/P/MP002XW12WY2_26...,lamoda_photos/Kappa_Kappa_Кроссовки_SIERRA_MES...,//a.lmcdn.ru/product/M/P/MP002XW12WY2_26197854...
3,Kappa,Kappa Кроссовки SIERRA MESH,Кроссовки,67545,NaN,https://a.lmcdn.ru/product/M/P/MP002XW12WY2_26...,lamoda_photos/Kappa_Kappa_Кроссовки_SIERRA_MES...,//a.lmcdn.ru/product/M/P/MP002XW12WY2_26197854...
4,Kappa,Kappa Кроссовки SIERRA MESH,Кроссовки,67545,NaN,https://a.lmcdn.ru/product/M/P/MP002XW12WY2_26...,lamoda_photos/Kappa_Kappa_Кроссовки_SIERRA_MES...,//a.lmcdn.ru/product/M/P/MP002XW12WY2_26197854...
...,...,...,...,...,...,...,...,...
2351,Baasploa,Baasploa Кроссовки,Низкие кроссовки,77514,Кроссовки выполнены из текстиля и подошва из E...,https://a.lmcdn.ru/product/M/P/MP002XW1E4IT_31...,lamoda_photos/Baasploa_Baasploa_Кроссовки__775...,//a.lmcdn.ru/product/M/P/MP002XW1E4IT_31820340...
2352,Baasploa,Baasploa Кроссовки,Низкие кроссовки,77514,Кроссовки выполнены из текстиля и подошва из E...,https://a.lmcdn.ru/product/M/P/MP002XW1E4IT_31...,lamoda_photos/Baasploa_Baasploa_Кроссовки__775...,//a.lmcdn.ru/product/M/P/MP002XW1E4IT_31820340...
2353,Baasploa,Baasploa Кроссовки,Низкие кроссовки,77514,Кроссовки выполнены из текстиля и подошва из E...,https://a.lmcdn.ru/product/M/P/MP002XW1E4IT_31...,lamoda_photos/Baasploa_Baasploa_Кроссовки__775...,//a.lmcdn.ru/product/M/P/MP002XW1E4IT_31820340...
2354,Baasploa,Baasploa Кроссовки,Низкие кроссовки,77514,Кроссовки выполнены из текстиля и подошва из E...,https://a.lmcdn.ru/product/M/P/MP002XW1E4IT_31...,lamoda_photos/Baasploa_Baasploa_Кроссовки__775...,//a.lmcdn.ru/product/M/P/MP002XW1E4IT_31820340...
2355,Baasploa,Baasploa Кроссовки,Низкие кроссовки,77514,Кроссовки выполнены из текстиля и подошва из E...,https://a.lmcdn.ru/product/M/P/MP002XW1E4IT_31...,lamoda_photos/Baasploa_Baasploa_Кроссовки__775...,//a.lmcdn.ru/product/M/P/MP002XW1E4IT_31820340...

In [4]:
# удаляем дубликаты
lamoda_data = lamoda_data.drop_duplicates(subset="title_photo")
print(len(lamoda_data))

2244

In [5]:
lamoda_data.iloc[3]["path_to_lamoda_photo"] == lamoda_data.iloc[6]["path_to_lamoda_photo"]

False

In [6]:
lamoda_data = lamoda_data.drop_duplicates(subset="path_to_lamoda_photo")
print(len(lamoda_data))

367

## CLIP emb

In [7]:
# инизацлизация модели для ембеддингов
model_name = "ViT-B/32" #338M params
model, preprocess = clip.load(model_name, device=device)

In [8]:
img_path = prefix_path+lamoda_data.iloc[1]["title_photo"]
image = Image.open(img_path).convert("RGB")
preproc_image = preprocess(image).unsqueeze(0).to(device)
with torch.no_grad():
    image_emb = model.encode_image(preproc_image)
image_emb.shape

torch.Size([1, 512])

In [9]:
def get_image_embedding_clip(img_path):
    image = Image.open(img_path).convert('RGB')

    preproc_image = preprocess(image).unsqueeze(0).to(device)
    with torch.no_grad():
        image_emb = model.encode_image(preproc_image)
        
    # Нормализуем эмбеддинг (это важно для поиска в Qdrant)
    image_emb /= image_emb.norm(dim=-1, keepdim=True)
    
    return image_emb.cpu().numpy().flatten()

In [10]:
def create_db(
        client: QdrantClient,
        collection_name: str, 
        emb_dim: int,
        data: pd.DataFrame,
        get_image_embedding: callable):
    
    if not client.collection_exists(collection_name):
        client.create_collection(
            collection_name=collection_name,
            vectors_config={
                 "photos": models.VectorParams(size=emb_dim, distance=models.Distance.COSINE)
            },
        )
        unprocessable = 0

        for idx, row in data.iterrows():
                img_path = prefix_path+lamoda_data.loc[idx]["title_photo"]
                try:
                    image_emb = get_image_embedding(img_path)

                    point = models.PointStruct(
                        id=idx, 
                        vector={
                             "photos" : image_emb.tolist()
                            }, 
                        payload={
                            "brand": row["brand"],
                            "model": row["model"],
                            "color": row["color"],
                            "path_to_photo": os.path.join(prefix_path, row["title_photo"]) # cохраняем путь для отображения!
                        }
                    )

                    client.upsert(
                        collection_name=collection_name, 
                        points=[point]
                        )
                except:
                    unprocessable+=1 
                    continue
        print("unprocessable: ", unprocessable)
    else:
        print("Коллекция уже существует")

In [12]:
emb_dim = 512
collection_name = "Sneakers_CLIP"

create_db(
        client,
        collection_name, 
        emb_dim,
        lamoda_data,
        get_image_embedding_clip)

unprocessable:  0

## Metrics CLIP

In [11]:
user_data = pd.read_csv(prefix_path+"user_data.csv", sep=";")
user_data = user_data.drop_duplicates()
user_data = user_data.drop_duplicates(subset="path_to_user_photo")
user_data = user_data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle data
print(len(user_data))

448

In [12]:
user_data

,brand,model,category,color,description,title_photo,path_to_title_photo,user_photo,path_to_user_photo
0,X-Plode,X-Plode Кроссовки,Низкие кроссовки,26114,NaN,//a.lmcdn.ru/product/M/P/MP002XW0VZPC_30825388...,lamoda_photos/X-Plode_X-Plode_Кроссовки__0.jpg,https://a.lmcdn.ru/photoreview/?key=a3f76460-f...,user_photos/X-Plode_X-Plode_Кроссовки__26114_1...
1,Founds,Founds Кроссовки,Низкие кроссовки,4993,NaN,//a.lmcdn.ru/product/R/T/RTLAER098401_32019644...,lamoda_photos/Founds_Founds_Кроссовки__0.jpg,https://a.lmcdn.ru/photoreview/?key=f4d48963-8...,user_photos/Founds_Founds_Кроссовки__4993_0.jpg
2,Lacoste,Lacoste Кеды BASESHOT PRO,Низкие кеды,33494,NaN,//a.lmcdn.ru/product/M/P/MP002XW1FS8B_26593567...,lamoda_photos/Lacoste_Lacoste_Кеды_BASESHOT_PR...,https://a.lmcdn.ru/photoreview/?key=f067d92c-f...,user_photos/Lacoste_Lacoste_Кеды_BASESHOT_PRO_...
3,X-Plode,X-Plode Кроссовки,Низкие кроссовки,78029,NaN,//a.lmcdn.ru/product/M/P/MP002XW0VZPD_30825747...,lamoda_photos/X-Plode_X-Plode_Кроссовки__0.jpg,https://a.lmcdn.ru/photoreview/?key=4195cf27-9...,user_photos/X-Plode_X-Plode_Кроссовки__78029_1...
4,Columbia,Columbia Кроссовки CRESTWOOD™,Низкие кроссовки,10099,Кроссовки с комбинированным верхом из натураль...,//a.lmcdn.ru/product/M/P/MP002XW02YFS_12636285...,lamoda_photos/Columbia_Columbia_Кроссовки_CRES...,https://a.lmcdn.ru/photoreview/?key=1b486e7b-f...,user_photos/Columbia_Columbia_Кроссовки_CRESTW...
...,...,...,...,...,...,...,...,...,...
443,Ecco,Ecco Кеды SOFT 7 W,Низкие кеды,547,NaN,//a.lmcdn.ru/product/M/P/MP002XW0S0Z2_11057679...,lamoda_photos/Ecco_Ecco_Кеды_SOFT_7_W_0.jpg,https://a.lmcdn.ru/photoreview/?key=decae862-b...,user_photos/Ecco_Ecco_Кеды_SOFT_7_W_0.jpg
444,Kappa,Kappa Кроссовки SELECTO MD,Кроссовки,93057,"Кроссовки выполнены из синтетической кожи, доп...",//a.lmcdn.ru/product/M/P/MP002XW0OTPY_22083371...,lamoda_photos/Kappa_Kappa_Кроссовки_SELECTO_MD...,https://a.lmcdn.ru/photoreview/?key=70c0ac26-b...,user_photos/Kappa_Kappa_Кроссовки_SELECTO_MD_2...
445,Karl Lagerfeld,Karl Lagerfeld Кеды,Низкие кеды,72503,NaN,//a.lmcdn.ru/product/M/P/MP002XW1DF5T_31481364...,lamoda_photos/Karl_Lagerfeld_Karl_Lagerfeld_Ке...,https://a.lmcdn.ru/photoreview/?key=757e82fc-0...,user_photos/Karl_Lagerfeld_Karl_Lagerfeld_Кеды...
446,Pierre Cardin,Pierre Cardin Кеды,Низкие кеды,53065,NaN,//a.lmcdn.ru/product/M/P/MP002XW1FBNU_26660772...,lamoda_photos/Pierre_Cardin_Pierre_Cardin_Кеды...,https://a.lmcdn.ru/photoreview/?key=a362e9b7-e...,user_photos/Pierre_Cardin_Pierre_Cardin_Кеды__...
447,Nike,Nike Кроссовки W ZOOM FLY 6,Низкие кроссовки,37140,Кроссовки выполнены из текстиля. Модель для бе...,//a.lmcdn.ru/product/R/T/RTLAFA041201_32122761...,lamoda_photos/Nike_Nike_Кроссовки_W_ZOOM_FLY_6...,https://a.lmcdn.ru/photoreview/?key=fae500f5-c...,user_photos/Nike_Nike_Кроссовки_W_ZOOM_FLY_6_0...

In [13]:
test_data = user_data[-100:]
image_reference = dict(zip(test_data["path_to_user_photo"], test_data["model"]))

In [14]:
def count_metrics(
        collection_name: str,
        get_image_embedding: callable):

    recall_5 = 0
    recall_10 = 0
    accuracy = 0
    query_time = []
    N = 0
    unprocessable = []

    for image_path, reference_model in image_reference.items():
        try:
            start = time.perf_counter()
            query = get_image_embedding(prefix_path+image_path)
            candidates = client.query_points(
                                        collection_name=collection_name,
                                        query=query, 
                                        using="photos",
                                        limit=10,           
                                        with_payload=True   # Возвращаем бренд, модель и путь из CSV
                                    ).points
            end = time.perf_counter()
        
            results = [candidate.payload.get("model") for candidate in candidates]
            if reference_model in results:
                recall_10 += 1
            if reference_model in results[:5]:
                recall_5 += 1
            if reference_model == results[0]:
                accuracy += 1
            query_time.append(end-start)
            N +=1

        except:
            unprocessable.append(image_path)
            continue

    print("Unprocessable: ", len(unprocessable))

    return recall_10 *100 / N, recall_5 * 100 / N, accuracy * 100 / N, np.mean(query_time)

In [18]:
recall_10_clip, recall_5_clip, accuracy_clip, avg_query_time_clip = count_metrics(collection_name, get_image_embedding_clip)

Unprocessable:  0

In [19]:
df_data = {
    "Accuracy" : [accuracy_clip],
    "Recall@5": [recall_5_clip], 
    "Recall@10": [recall_10_clip],
    "Avg_query_time": [avg_query_time_clip]
}
  
table = pd.DataFrame(data=df_data)
table

   Accuracy  Recall@5  Recall@10  Avg_query_time
0      20.0      34.0       47.0        0.044016

## DINO emb

In [14]:
model_name = 'facebook/dinov2-large' #300M params


processor = AutoImageProcessor.from_pretrained(model_name)
model_dino = AutoModel.from_pretrained(model_name, device_map="auto")

Loading weights: 100%|██████████| 439/439 [00:00<00:00, 510.12it/s]

In [15]:
img_path = "/home/inna/Рабочий стол/SneakerSearch/scripts/lamoda_photos/Under_Armour_Under_Armour_Кроссовки_UA_W_Charged_P_0.jpg"
image = Image.open(img_path).convert("RGB")


inputs = processor(images=image, return_tensors="pt").to(device)
with torch.inference_mode():
    outputs = model_dino(**inputs)
    image_emb = outputs.last_hidden_state[:, 0, :] # CLS-token

image_emb.shape

torch.Size([1, 1024])

In [16]:
def get_image_embedding_dino(img_path):
    image = Image.open(img_path).convert('RGB')
    
    preproc_image = processor(images=image, return_tensors="pt").to(device)
    with torch.inference_mode():
        outputs = model_dino(**preproc_image)
        image_emb = outputs.last_hidden_state[:, 0, :] # CLS-token
        # Нормализуем эмбеддинг (это важно для поиска в Qdrant)
        image_emb /= image_emb.norm(dim=-1, keepdim=True)
    
    return image_emb.cpu().numpy().flatten()

In [38]:
emb_dim = 1024
collection_name = "Sneakers_DINO"

create_db(
        client,
        collection_name, 
        emb_dim,
        lamoda_data,
        get_image_embedding_dino)

unprocessable:  0

In [39]:
recall_10_dino, recall_5_dino, accuracy_dino, avg_query_time_dino = count_metrics(collection_name, get_image_embedding_dino)

Unprocessable:  0

In [40]:
df_data = {
    "Accuracy" : [accuracy_clip, accuracy_dino],
    "Recall@5": [recall_5_clip, recall_5_dino], 
    "Recall@10": [recall_10_clip, recall_10_dino],
    "Avg_query_time": [avg_query_time_clip, avg_query_time_dino]
}
  
table = pd.DataFrame(data=df_data)
table

   Accuracy  Recall@5  Recall@10  Avg_query_time
0      20.0      34.0       47.0        0.044016
1       3.0      13.0       19.0        0.277981

## Mультивекторность Qdrant

**ЧТО:** 

В Qdrant реализованы два основных подхода к работе с несколькими векторами:
1. Именованные векторы (Named Vectors). Этот метод используется, когда один объект нужно описать разными характеристиками или модальностями. Если объединить эти эмбеддинги, получется много вариантов одного и того же объекта
2. Мультивекторные представления и Late Interaction. Более сложный механизм, предназначенный для моделей вроде ColBERT или ColPali, где один документ представляется не одним вектором, а набором векторов (например, по одному на каждый токен или фрагмент изображения). Если объединить эти эмбеддинги, получится представляемый ими объект.

MaxSim: Qdrant использует оператор MaxSim для вычисления сходства. Он находит наиболее похожий вектор в документе для каждого вектора в поисковом запросе и суммирует эти показатели

**ЗАЧЕМ:**

Можно же было бы создать для каждого ракурса свою точку в ВБД
1) Дедупликация в выдаче - не выдаст 3 одинаковые модели, потому что запрос похож на 3 ракурса одной модели. Всегда будут РАЗНЫЕ модели.
2) Управление данными (CRUD) - при необходимости обновить точку, надо будет обновить одну, а не искать все точки, принадлежащие этой модели
3) Производительность и индексы - используется специальный тип сжатия и индексации. В случае с max_sim Qdrant оптимизирует поиск так, чтобы не сравнивать запрос с каждым вектором в лоб, а использовать аппроксимацию.

In [15]:
lamoda_data_racurses = pd.read_csv(prefix_path+"lamoda_data.csv", sep=";")
lamoda_data_racurses = lamoda_data_racurses.drop_duplicates(subset="title_photo")
print(len(lamoda_data_racurses))

2244

In [16]:
grouped = lamoda_data_racurses.groupby(['brand', 'model', 'color'])['title_photo'].apply(list).reset_index()
print(grouped)

            brand                                       model  color  \
0             361                    361 Кроссовки CENTAURI 2  17296
1          4forms                                4forms Кеды    3588
2            ACBC  ACBC Кроссовки LOW TOP WOMAN ECO MATERIALS  40124
3           ASICS                   ASICS Кроссовки FUJISPEED  42637
4           ASICS               ASICS Кроссовки GEL-KAYANO 32  46422
..            ...                                         ...    ...
374  adidas YEEZY   adidas YEEZY Кроссовки YEEZY BOOST 350 V2  21383
375      s.Oliver                         s.Oliver Кроссовки   54994
376          Араз                             Араз Кроссовки   10798
377      Два Мяча                              Два Мяча Кеды   29971
378      Два Мяча                              Два Мяча Кеды   67693

                                           title_photo
0    [lamoda_photos/361_361_Кроссовки_CENTAURI_2_17...
1    [lamoda_photos/4forms_4forms_Кеды__3588_0.jpg,...
2    [lamoda_photos/ACBC_ACBC_Кроссовки_LOW_TOP_WOM...
3    [lamoda_photos/ASICS_ASICS_Кроссовки_FUJISPEED...
4    [lamoda_photos/ASICS_ASICS_Кроссовки_GEL-KAYAN...
..                                                 ...
374  [lamoda_photos/adidas_YEEZY_adidas_YEEZY_Кросс...
375  [lamoda_photos/s.Oliver_s.Oliver_Кроссовки__54...
376  [lamoda_photos/Араз_Араз_Кроссовки__10798_0.jp...
377  [lamoda_photos/Два_Мяча_Два_Мяча_Кеды__29971_0...
378  [lamoda_photos/Два_Мяча_Два_Мяча_Кеды__67693_0...

[379 rows x 4 columns]

In [31]:
def create_multivector_db(
        client: QdrantClient,
        collection_name: str, 
        emb_dim: int,
        data: pd.DataFrame,
        get_image_embedding: callable):
    
    unprocessable = 0
    
    if not client.collection_exists(collection_name):
        client.create_collection(
            collection_name=collection_name,
            vectors_config={
                "photos": models.VectorParams(
                    size=emb_dim, 
                    distance=models.Distance.COSINE,
                    multivector_config=models.MultiVectorConfig(
                        comparator=models.MultiVectorComparator.MAX_SIM #позволяет хранить список векторов под одним именем
                    ) 
                )
            }
        )

        for idx, row in data.iterrows():
            try:
                multivector = []
                for racurs in row["title_photo"]:
                    try:
                        img_path = prefix_path + racurs
                        img_emb = get_image_embedding(img_path)
                        multivector.append(img_emb.tolist())
                    except:
                        continue

                point = models.PointStruct(
                    id=idx, 
                    vector={
                        "photos": multivector
                        }, 
                    payload={
                        "brand": row["brand"],
                        "model": row["model"],
                        "color": row["color"],
                        "path_to_photo": os.path.join(prefix_path, row["title_photo"][0]) # cохраняем путь для отображения!
                    }
                )

                client.upsert(
                    collection_name=collection_name, 
                    points=[point]
                    )
                    
            except: 
                unprocessable+=1
                continue
        print("unprocessable: ", unprocessable)
    else:
        print("Коллекция уже существует")

In [34]:
collection_name = "Sneakers_CLIP_multivector"

create_multivector_db(
    client,
    collection_name, 
    emb_dim = 512,
    data = grouped,
    get_image_embedding=get_image_embedding_clip)

unprocessable:  0

In [ ]:
recall_10_clip_multivectors, recall_5_clip_multivectors, accuracy_clip_multivectors, avg_query_time_clip_multivectors = count_metrics(collection_name, get_image_embedding_clip)

df_data = {
    "Accuracy" : [accuracy_clip, accuracy_dino, accuracy_clip_multivectors],
    "Recall@5": [recall_5_clip, recall_5_dino, recall_5_clip_multivectors], 
    "Recall@10": [recall_10_clip, recall_10_dino, recall_10_clip_multivectors],
    "Avg_query_time": [avg_query_time_clip, avg_query_time_dino, avg_query_time_clip_multivectors]
}
  
table = pd.DataFrame(data=df_data)
table

   Accuracy  Recall@5  Recall@10  Avg_query_time
0      20.0      34.0       47.0        0.044016
1       3.0      13.0       19.0        0.277981
2      23.0      39.0       45.0        0.034411

In [36]:
collection_name = "Sneakers_DINO_multivector"

create_multivector_db(
    client,
    collection_name, 
    emb_dim = 1024,
    data = grouped,
    get_image_embedding=get_image_embedding_dino)

unprocessable:  0

In [ ]:
recall_10_dino_multivectors, recall_5_dino_multivectors, accuracy_dino_multivectors, avg_query_time_dino_multivectors = count_metrics(collection_name, get_image_embedding_dino)

df_data = {
    "Accuracy" : [accuracy_clip, accuracy_dino, accuracy_clip_multivectors, accuracy_dino_multivectors],
    "Recall@5": [recall_5_clip, recall_5_dino, recall_5_clip_multivectors, recall_5_dino_multivectors], 
    "Recall@10": [recall_10_clip, recall_10_dino, recall_10_clip_multivectors, recall_10_dino_multivectors],
    "Avg_query_time": [avg_query_time_clip, avg_query_time_dino, avg_query_time_clip_multivectors, avg_query_time_dino_multivectors]
}
  
table = pd.DataFrame(data=df_data, index=["CLIP-ViT", "DINOv2", "CLIP_multivector", "DINO_multivector"])
table

                  Accuracy  Recall@5  Recall@10  Avg_query_time
CLIP-ViT              20.0      34.0       47.0        0.044016
DINOv2                 3.0      13.0       19.0        0.277981
CLIP_multivector      23.0      39.0       45.0        0.034411
DINO_multivector       6.0      13.0       18.0        0.274234

In [43]:
pd.options.display.float_format = '{:.2f}'.format
pd.DataFrame(
    data={
        "CLIP-ViT" : [accuracy_clip, recall_5_clip, recall_10_clip, avg_query_time_clip, 15.4],
        "DINOv2": [accuracy_dino, recall_5_dino, recall_10_dino, avg_query_time_dino, 76.5],
        "CLIP_multivector" : [accuracy_clip_multivectors, recall_5_clip_multivectors, recall_10_clip_multivectors,avg_query_time_clip_multivectors, 100.1],
        "DINO_multivector": [accuracy_dino_multivectors, recall_5_dino_multivectors, recall_10_dino_multivectors, avg_query_time_dino_multivectors, 279.3]
    },
    index = ["Accuracy", "Recall@5", "Recall@10", "Avg_query_time, s", "Create_DB_time, s"]
)

                   CLIP-ViT  DINOv2  CLIP_multivector  DINO_multivector
Accuracy              20.00    3.00             23.00              6.00
Recall@5              34.00   13.00             39.00             13.00
Recall@10             47.00   19.00             45.00             18.00
Avg_query_time, s      0.04    0.28              0.03              0.27
Create_DB_time, s     15.40   76.50            100.10            279.30

## Mulvis (IVF index)

In [44]:
milvus_client = MilvusClient("./milvus_local.db")

In [45]:
def create_milvus_bd(
        collection_name: str, 
        emb_dim: int, 
        data: pd.DataFrame,
        get_image_embedding: callable):
    # Создаем схему и коллекцию для CLIP
    schema = milvus_client.create_schema(auto_id=False)
    schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
    schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=emb_dim)
    schema.add_field(field_name="brand", datatype=DataType.VARCHAR, max_length=500)
    schema.add_field(field_name="model", datatype=DataType.VARCHAR, max_length=500)
    schema.add_field(field_name="path_to_photo", datatype=DataType.VARCHAR, max_length=500)

    milvus_client.create_collection(collection_name=collection_name, schema=schema)

    # Создаем IVF индекс
    index_params = milvus_client.prepare_index_params()
    index_params.add_index(
        field_name="vector",
        index_type="IVF_FLAT",
        metric_type="COSINE",
        params={"nlist": 1024}
    )
    milvus_client.create_index(collection_name=collection_name, index_params=index_params)

    #Добавление данных
    unprocessable = 0
    for idx, row in data.iterrows():
        img_path = prefix_path+row["title_photo"]
        try:
            image_emb = get_image_embedding(img_path)
            image_emb = image_emb.astype('float32')

            res = milvus_client.insert(
                collection_name=collection_name,
                data=[
                    {
                        "id": idx, 
                        "vector": image_emb,
                        "brand": row["brand"],
                        "model": row["model"],
                        "path_to_photo": os.path.join(prefix_path, row["title_photo"][0]) 
                        }
                        ]
            )
        except:
            unprocessable+=1
            continue
    print("unprocessable: ", unprocessable)

In [50]:
collection_name = "CLIP_IVF"
emb_dim = 512

create_milvus_bd(collection_name, emb_dim, lamoda_data, get_image_embedding_clip)

unprocessable:  0

In [51]:
#milvus_client.describe_collection(collection_name)
#milvus_client.drop_collection(collection_name=collection_name)

stats = milvus_client.get_collection_stats(collection_name=collection_name)
print(f"Количество точек: {stats['row_count']}")

Количество точек: 367

In [54]:
def count_metrics_milvus(collection_name, get_image_embedding):

    recall_5 = 0
    recall_10 = 0
    accuracy = 0
    query_time = []
    N = 0
    unprocessable = []

    for image_path, reference_model in image_reference.items():
        try:
            start = time.perf_counter()
            query = get_image_embedding(prefix_path+image_path)
            query = query.astype('float32')
            candidates = milvus_client.search(
                                        collection_name=collection_name,
                                        data=[query], 
                                        limit=10,
                                        search_params={"params": {"nprobe": 10}},
                                         output_fields=["brand", "model"]
                                    )
            end = time.perf_counter()
        
            results = [candidate["model"] for candidate in candidates[0]]
            if reference_model in results:
                recall_10 += 1
            if reference_model in results[:5]:
                recall_5 += 1
            if reference_model == results[0]:
                accuracy += 1
            query_time.append(end-start)
            N +=1

        except:
            unprocessable.append(image_path)
            continue

    print("Unprocessable: ", len(unprocessable))

    return recall_10 *100 / N, recall_5 * 100 / N, accuracy * 100 / N, np.mean(query_time)

In [55]:
recall_10_clip_ivf, recall_5_clip_ivf, accuracy_clip_ivf, avg_query_time_clip_ivf = count_metrics_milvus(collection_name, get_image_embedding_clip)

I0511 14:44:16.265460  732400 chttp2_transport.cc:1369] unix:/tmp/tmptmi3wnmz_milvus_local.db.sock: Got goaway [11] err=UNAVAILABLE:GOAWAY received; Error code: 11; Debug Text: too_many_pings {grpc_status:14, http2_error:11}
E0511 14:44:16.265534  732400 chttp2_transport.cc:1401] unix:/tmp/tmptmi3wnmz_milvus_local.db.sock: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 10000ms

Unprocessable:  0

In [56]:
pd.options.display.float_format = '{:.2f}'.format
pd.DataFrame(
    data={
        "CLIP-ViT" : [accuracy_clip, recall_5_clip, recall_10_clip, avg_query_time_clip, 15.4],
        "DINOv2": [accuracy_dino, recall_5_dino, recall_10_dino, avg_query_time_dino, 76.5],
        "CLIP_multivector" : [accuracy_clip_multivectors, recall_5_clip_multivectors, recall_10_clip_multivectors,avg_query_time_clip_multivectors, 100.1],
        "DINO_multivector": [accuracy_dino_multivectors, recall_5_dino_multivectors, recall_10_dino_multivectors, avg_query_time_dino_multivectors, 279.3],
        "CLIP_Milvus_IVF" : [accuracy_clip_ivf, recall_5_clip_ivf, recall_10_clip_ivf, avg_query_time_clip_ivf, 15.0]
    },
    index = ["Accuracy", "Recall@5", "Recall@10", "Avg_query_time, s", "Create_DB_time, s"]
)

,CLIP-ViT,DINOv2,CLIP_multivector,DINO_multivector,CLIP_Milvus_IVF
Accuracy,20.00,3.00,23.00,6.00,20.00
Recall@5,34.00,13.00,39.00,13.00,34.00
Recall@10,47.00,19.00,45.00,18.00,47.00
"Avg_query_time, s",0.04,0.28,0.03,0.27,0.03
"Create_DB_time, s",15.40,76.50,100.10,279.30,15.00

In [58]:
# DINOv2 + Milvus_IVF

collection_name = "DINO_IVF"
emb_dim = 1024

create_milvus_bd(collection_name, emb_dim, lamoda_data, get_image_embedding_dino)

unprocessable:  0

In [59]:
stats = milvus_client.get_collection_stats(collection_name=collection_name)
print(f"Количество точек: {stats['row_count']}")

Количество точек: 367

In [61]:
recall_10_dino_ivf, recall_5_dino_ivf, accuracy_dino_ivf, avg_query_time_dino_ivf = count_metrics_milvus(collection_name, get_image_embedding_dino)

Unprocessable:  0

In [62]:
pd.DataFrame(
    data={
        "CLIP-ViT" : [accuracy_clip, recall_5_clip, recall_10_clip, avg_query_time_clip, 15.4],
        "DINOv2": [accuracy_dino, recall_5_dino, recall_10_dino, avg_query_time_dino, 76.5],
        "CLIP_multivector" : [accuracy_clip_multivectors, recall_5_clip_multivectors, recall_10_clip_multivectors,avg_query_time_clip_multivectors, 100.1],
        "DINO_multivector": [accuracy_dino_multivectors, recall_5_dino_multivectors, recall_10_dino_multivectors, avg_query_time_dino_multivectors, 279.3],
        "CLIP_Milvus_IVF" : [accuracy_clip_ivf, recall_5_clip_ivf, recall_10_clip_ivf, avg_query_time_clip_ivf, 15.0],
        "DINO_Milvus_IVF" : [accuracy_dino_ivf, recall_5_dino_ivf, recall_10_dino_ivf, avg_query_time_dino_ivf, 22.6]
    },
    index = ["Accuracy", "Recall@5", "Recall@10", "Avg_query_time, s", "Create_DB_time, s"]
)

,CLIP-ViT,DINOv2,CLIP_multivector,DINO_multivector,CLIP_Milvus_IVF,DINO_Milvus_IVF
Accuracy,20.00,3.00,23.00,6.00,20.00,3.00
Recall@5,34.00,13.00,39.00,13.00,34.00,13.00
Recall@10,47.00,19.00,45.00,18.00,47.00,19.00
"Avg_query_time, s",0.04,0.28,0.03,0.27,0.03,0.08
"Create_DB_time, s",15.40,76.50,100.10,279.30,15.00,22.60

## Preprocessing

Для фильтрации фотографий, не содержащих кроссовки проверяется 2 варианта:

1) Использование модели для детекции объектов YOLOS, предобученной на датасете fashionpedia (46781 images, 342182 bounding-boxes, num_classes=46, names=46) с элементами одежды (в том числе обувь, class=5 "shoe"). Мотивация применения подобных моделей обучсловена тем, что на выходе получаем не только ответ на вопрос "присутствуют ли кроссовки на фотографии?", но и bounding-box, позволяющий обрезать лишние части картинки и далее работать непосредственно с изображением кроссовка.

Без дообучения, данная модель не распознала ни одного кроссовка как на бытовых пользовательских фотографиях, так и на студийных, несмотря на снижение порога детекции до 0.1. Вследствие чего такой подход может быть применен только после дообучения на размеченных данных. 

2) Использование легкой сверточной модели Mobilenet, с заменой выходного слоя на классификацию на 2 класса "на фото есть кроссовки" и "на фото нет кроссовок". Эмпирически определен уровень вероятности 0.4 при котором модель в 100% случаев определяет на студийных фото наличие кроссовок, и в 95% случаев на бытовых пользовательских фотографиях. В 5% отсеяных фото попали фотографии подошвы, макрофото части носка, либо фото, на которых кроссовки занимают очень маленький процент изображения.

In [ ]:
# YOLOS_FT_FASHIONPEDIA

from transformers import  AutoModelForObjectDetection

object_detection_model_name = "valentinafevu/yolos-fashionpedia"
image_processor = AutoImageProcessor.from_pretrained(object_detection_model_name)
model_yolo = AutoModelForObjectDetection.from_pretrained(object_detection_model_name)

Loading weights: 100%|██████████| 212/212 [00:00<00:00, 6825.61it/s]

In [113]:
model_yolo.to(device)

YolosForObjectDetection(
  (vit): YolosModel(
    (embeddings): YolosEmbeddings(
      (patch_embeddings): YolosPatchEmbeddings(
        (projection): Conv2d(3, 384, kernel_size=(16, 16), stride=(16, 16))
      )
      (dropout): Dropout(p=0.0, inplace=False)
      (interpolation): InterpolateInitialPositionEmbeddings()
    )
    (encoder): YolosEncoder(
      (layer): ModuleList(
        (0-11): 12 x YolosLayer(
          (attention): YolosAttention(
            (attention): YolosSelfAttention(
              (query): Linear(in_features=384, out_features=384, bias=True)
              (key): Linear(in_features=384, out_features=384, bias=True)
              (value): Linear(in_features=384, out_features=384, bias=True)
            )
            (output): YolosSelfOutput(
              (dense): Linear(in_features=384, out_features=384, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
          )
          (intermediate): YolosIntermediate(
            (dense): Linear(in_features=384, out_features=1536, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): YolosOutput(
            (dense): Linear(in_features=1536, out_features=384, bias=True)
            (dropout): Dropout(p=0.0, inplace=False)
          )
          (layernorm_before): LayerNorm((384,), eps=1e-12, elementwise_affine=True)
          (layernorm_after): LayerNorm((384,), eps=1e-12, elementwise_affine=True)
        )
      )
      (interpolation): InterpolateMidPositionEmbeddings()
    )
    (layernorm): LayerNorm((384,), eps=1e-12, elementwise_affine=True)
  )
  (class_labels_classifier): YolosMLPPredictionHead(
    (layers): ModuleList(
      (0-1): 2 x Linear(in_features=384, out_features=384, bias=True)
      (2): Linear(in_features=384, out_features=47, bias=True)
    )
  )
  (bbox_predictor): YolosMLPPredictionHead(
    (layers): ModuleList(
      (0-1): 2 x Linear(in_features=384, out_features=384, bias=True)
      (2): Linear(in_features=384, out_features=4, bias=True)
    )
  )
)

In [ ]:
is_sneakers = 0
no_sneakers = 0
for image_path, reference_model in image_reference.items():
    img_path = prefix_path+image_path
    image = Image.open(img_path).convert('RGB')

    with torch.no_grad():
        inputs = image_processor(images=[image], return_tensors="pt")
        outputs = model_yolo(**inputs.to(device))
        target_sizes = torch.tensor([[image.size[1], image.size[0]]])
        results = image_processor.post_process_object_detection(outputs, threshold=0.1, target_sizes=target_sizes)[0]
    if 5 in results["labels"]:
        is_sneakers += 1
    else: 
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  0  no_sneakers:  100

In [143]:
is_sneakers = 0
no_sneakers = 0
for idx, row in lamoda_data[:100].iterrows():
    img_path = prefix_path+row["title_photo"]
    image = Image.open(img_path).convert('RGB')
   
    with torch.no_grad():
        inputs = image_processor(images=[image], return_tensors="pt")
        outputs = model_yolo(**inputs.to(device))
        target_sizes = torch.tensor([[image.size[1], image.size[0]]])
        results = image_processor.post_process_object_detection(outputs, threshold=0.1, target_sizes=target_sizes)[0]
    if 5 in results["labels"]:
        is_sneakers += 1
    else: 
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  0  no_sneakers:  100

In [67]:
# MOBILENET_V3_LARGE

import torchvision.models as models

mobilenet = models.mobilenet_v3_large(weights="IMAGENET1K_V2")

In [74]:
mobilenet.to(device)

MobileNetV3(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): Hardswish()
    )
    (1): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=16, bias=False)
          (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (2): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=64, bias=False)
          (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(64, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(24, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (3): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(24, 72, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(72, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(72, 72, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=72, bias=False)
          (1): BatchNorm2d(72, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(72, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(24, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (4): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(24, 72, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(72, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(72, 72, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=72, bias=False)
          (1): BatchNorm2d(72, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(72, 24, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(24, 72, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(72, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(40, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (5): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(40, 120, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(120, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(120, 120, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=120, bias=False)
          (1): BatchNorm2d(120, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(120, 32, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(32, 120, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(120, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(40, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (6): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(40, 120, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(120, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(120, 120, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=120, bias=False)
          (1): BatchNorm2d(120, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(120, 32, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(32, 120, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(120, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(40, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (7): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(240, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(240, 240, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=240, bias=False)
          (1): BatchNorm2d(240, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(80, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (8): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(80, 200, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(200, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(200, 200, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=200, bias=False)
          (1): BatchNorm2d(200, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(200, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(80, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (9): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(80, 184, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(184, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(184, 184, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=184, bias=False)
          (1): BatchNorm2d(184, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(184, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(80, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (10): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(80, 184, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(184, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(184, 184, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=184, bias=False)
          (1): BatchNorm2d(184, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(184, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(80, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (11): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(480, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
          (1): BatchNorm2d(480, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(480, 120, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(120, 480, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(112, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (12): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(672, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(672, 672, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=672, bias=False)
          (1): BatchNorm2d(672, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(672, 168, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(168, 672, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(112, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (13): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(672, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(672, 672, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=672, bias=False)
          (1): BatchNorm2d(672, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(672, 168, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(168, 672, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(672, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(160, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (14): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(960, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(960, 960, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=960, bias=False)
          (1): BatchNorm2d(960, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(960, 240, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(240, 960, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(960, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(160, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (15): InvertedResidual(
      (block): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(960, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(960, 960, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=960, bias=False)
          (1): BatchNorm2d(960, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
          (2): Hardswish()
        )
        (2): SqueezeExcitation(
          (avgpool): AdaptiveAvgPool2d(output_size=1)
          (fc1): Conv2d(960, 240, kernel_size=(1, 1), stride=(1, 1))
          (fc2): Conv2d(240, 960, kernel_size=(1, 1), stride=(1, 1))
          (activation): ReLU()
          (scale_activation): Hardsigmoid()
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(960, 160, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(160, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        )
      )
    )
    (16): Conv2dNormActivation(
      (0): Conv2d(160, 960, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (1): BatchNorm2d(960, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): Hardswish()
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=1)
  (classifier): Sequential(
    (0): Linear(in_features=960, out_features=1280, bias=True)
    (1): Hardswish()
    (2): Dropout(p=0.2, inplace=True)
    (3): Linear(in_features=1280, out_features=2, bias=True)
  )
)

In [69]:
for param in mobilenet.parameters():
    param.requires_grad = False

# В MobileNetV3 классификатор находится в атрибуте .classifier
# Последний слой там — линейный под индексом [1]
num_features = mobilenet.classifier[3].in_features
mobilenet.classifier[3] = torch.nn.Linear(num_features, 2) # 2 класса: "есть кроссовки" и "нет"

print(mobilenet.classifier)

Sequential(
  (0): Linear(in_features=960, out_features=1280, bias=True)
  (1): Hardswish()
  (2): Dropout(p=0.2, inplace=True)
  (3): Linear(in_features=1280, out_features=2, bias=True)
)

In [75]:
from torchvision import transforms

#трансформации для mobilenet
mobilenet_preprocess = transforms.Compose([
    transforms.Resize(256),                  # изменяем размер меньшей стороны до 256
    transforms.CenterCrop(224),              # обрезаем центр до 224x224
    transforms.ToTensor(),                   # переводим в тензор и нормализуем в [0, 1]
    transforms.Normalize(                    # стандартная нормализация для ImageNet
        mean=[0.485, 0.456, 0.406], 
        std=[0.229, 0.224, 0.225]
    ),
])


def sneakers_classifier(img_path):

    image = Image.open(img_path).convert("RGB") 
    prerpoc_image = mobilenet_preprocess(image)                     
    input = torch.unsqueeze(prerpoc_image, 0) 
    input = input.to(device)
         
    with torch.no_grad():
        output = mobilenet(input)

    probabilities = torch.nn.functional.softmax(output[0], dim=0)
    #print(f"Вероятность кроссовок: {probabilities[0].item():.2%}")
    return probabilities[0].item()

In [76]:
# юзерские фото с кроссовками

mobilenet.eval() 

NO_SNEAKERS=[]
is_sneakers = 0
no_sneakers = 0
for image_path, reference_model in image_reference.items():
    img_path = prefix_path+image_path
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
    else:
        NO_SNEAKERS.append(image_path)
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  95  no_sneakers:  5

In [77]:
NO_SNEAKERS

['user_photos/adidas_Originals_adidas_Originals_Кеды_GAZELLE_LO__2.jpg',
 'user_photos/adidas_adidas_Кроссовки_RUN_60s_4.0_0.jpg',
 'user_photos/adidas_adidas_Кроссовки_ADIZERO_EVO_SL_EXO_W_0.jpg',
 'user_photos/adidas_adidas_Кроссовки_Barricade_14_W_0.jpg',
 'user_photos/Salamander_Salamander_Кеды_Lamoda_Online_Exclusive_0.jpg']

In [78]:
# студийные фото кроссовок

NO_SNEAKERS = []

is_sneakers = 0
no_sneakers = 0
for idx, row in lamoda_data[:100].iterrows():
    img_path = prefix_path+row["title_photo"]
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
    else:
        NO_SNEAKERS.append(img_path)
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  100  no_sneakers:  0

In [81]:
# все не кроссовки

IS_SNEAKERS=[]
is_sneakers = 0
no_sneakers = 0
for file in os.listdir("/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers"):
    img_path = prefix_path+"No_sneakers/"+file
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
        IS_SNEAKERS.append(img_path)
    else:
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  185  no_sneakers:  14

In [82]:
IS_SNEAKERS

['/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/cjrzju9pwjlb1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_17935.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kot_Novyj_god_sharik_5529.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_nogi_11902.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557638_28-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-62.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_obuv_1386.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_9764.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kniga_nogi_8055.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_sport_serfing_1334.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/7957394408.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/92045f734fa8ec5e3d076ba6cd6054a0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/Ue929f670f945415490bdc1f65c8c3c15D.jpg_960x960.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/gitara_12259.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/s-l225 (1).jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo-2023-09-14-19-57-46.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo-2021-11-16-08-15-301.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_naushniki_32190.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo_2025-08-05_14-21-36-247x329.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_eda_26234.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_brunetka_eda_yajca_19506.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557664_6-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-12.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_myach_17624.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_nogi_flag_1626.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/colibri.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_deti_plyazh_17852.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/2008723182803_1773391334.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/d3bc73da-0d1f-40e4-92f1-2b083d6c451d.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_brunetka_mech_pirat_32011.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_prikol_7568.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_spinoj_34509.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/2gh1rymi0ur66ccq9d3exk5k5z4d0bcm.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/24_Darima_Togosheeva4.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kraski_8205.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/cvety_devochka_16598.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/spinoj_deti_bereg_12609.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1561556221174778147.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_pesok_29664.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1686558984169872559.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/16-na-labytenah.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/9eb967890cd2e56df6dfa33429418f0d.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devochka_s_kotenkom.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/8702180870.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_eda_23911.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/d2193bbed826d1537a5dba003e9b65f9_502_660.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_ochki_15390.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/eda_yagoda_11595.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_loshad_15520.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/shlyapa_deti_galstuk_18268.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_spinoj_platya_14858.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_snowboard_6356.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557643_32-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-71.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_15028.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_cvety_nasekomye_osa_28069.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_tigr_24050.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557661_24-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-56.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/5f444bcc-87b7-43db-a7b1-abf25b6e1284.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_spinoj_1871.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1686514505138778277.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/11.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/multfilm_luna_18383.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/ab09d6880e330d8291d7f149e29b6484e342807e_1024_1024.jpeg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_obuv_7067.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/ruki_myach_football_16284.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kot_shlyapa_Halloween_plasch_23562.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_nogi_2064.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_13086.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_31749.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo_2025-02-10_14-27-56-scaled.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_ptica_28388.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_motocikl_17885.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/funny-klev-club-p-smeshnie-kartinki-randomnie-8.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_19151.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_devushka_spinoj_34606.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_lisa_9402.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_kot_2199.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_sobaka_nogi_17424.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_obuv_2493.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/9077021247.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_basketball2.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/serial_deti_28807.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_film_znamenitost_29094.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/big_26489.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_23210.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_15128.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/serdce_igrushka_mishki_17626.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_23511.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/eda_morozhenoe_malina_10930.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_obuv_2495.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/voda_deti_19125.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_oruzhie_maska_24665.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_20758.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devochka_kniga_2457.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/galstuk_odezhda_31606.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_radost.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_eda_23896.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_10430.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_siluet_31102.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/W2184526_001.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_11832.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/dvlmdyzyttiamln1eyb1u3ihwzl0z89x.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/film_prikol_Batman_muzyka_1645.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/big_61389.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_sobaka_eda_2722.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_2574.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_sport_6466.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1.jpeg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_sobaka_deti_labrador_retriever_29543.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_prikol_cherepaha_16583.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/Lamborghini.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/ug1tr6xqbbtnfwsmkdnxut4s724jobxm.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_kot_sharf_1996.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/voda_nogi_30551.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/istockphoto-1475492416-612x612.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/chernye-3.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_voda_31405.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/eda_devushka_34152.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_lyzhi_1602.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/z2j42hnucccyr3lcqv4ngedrhjw62p7c.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_led_alpinism_26720.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557664_21-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-48.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_ptica_tukan_20514.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/multfilm_homyak_microfon_15474.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_topor_24923.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/none-428905003.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/f3ZHjstTZXionvsEF0r0FO_XGu9GzrLG3REtoyV3s4rKIzze7_Dr6-iHPQWeyCGzXIx2o_zypi8lARJhaqTYsvo6.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557617_26-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-59.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/cmp1umy9xymvg2c4gmedcwfq2gtz8bj1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/images.jpeg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/132830908467a36324d4bdc_medium.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_cvety_17683.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/z0pQhOJPgYltPKZ479zUkcZgyk4RSgNZ3GjLi0qu.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/-rJ6OGEr_mo.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/awjyfPZ.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/cvety_eda_tarelki_vilka_32888.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kot_obuv_3641.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/41599-9397192e.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/tg1682065522_1775_AQADvcgxG8-HEEp-file_573.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_platya_16680.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_sneg_26163.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/8086_320.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/pechat-i-izgotovlenie-korobok-dlya-obuvi-1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo_2025-02-10_14-27-47-scaled.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/Thicker-drawer-shoebox-transparent-shoe-box-men-and-women-drawer-style-shoes-storage-box-paper-box.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_motocikl_15192.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_krolik_21191.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo_2023-09-02_19-35-42.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/AQAFX7qNG7sbcIMHppnj9S5GEBZy-qCw-e3MDeMRhpkjl92Zz62-4avB1PVnjobGQwJn73EMseCejIFvvuP1AMvIDIk.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/10270.440@2x.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_platya_les_15589.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_telefon_6715.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/muzhchina_kniga_nogi_18461.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557634_1-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/chelovechek_v_galstuke.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nasekomye_bozhi_korovki_3514.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo-2021-11-16-08-15-282.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/mariyamosunovakorotkina004_1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557684_30-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-68.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_loshad_8237.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/d5cfb90d55a4d0fbdeef022813b71401.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_tigr_10666.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/c49083ef-fdb0-49d7-b9a7-e0e697cbef05.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devushka_kniga_okno_26499.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/c2c23966-494e-4456-a837-927e86184cb3.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/avto_5883.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/d6b42179-14ec-43e5-9462-f49e6414c3db.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/s-l225 (2).jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/zhivotnye_sobaka_avto_22203.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/UlZcVxTitoC1ACqoiaUt1w.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/big_56391.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/LR-04597.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/original.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sobaka_zhivotnye_galstuk_34091.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/ptica_nogi_kurica_17058.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/s-l225.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/multfilm_pingviny.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/myach_sport_33649.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/acosAC4BLWROzwiU3Ye-2PpCZmMn5_940zXs3PloUyDmskpAXnJs2p84nYwyzzF7L7jUomlGeiRfhJyET5ihSpqP.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/devochka_sport_konki_27823.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/272859a1-759d-4a92-bf4e-3b7de4925806.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557708_22-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-49.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557627_19-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-44.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/kostyum_krolika.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/1646557680_11-bigfoto-name-p-komnati-v-kvartire-realnie-prostie-deshevi-19.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/siluet_devochka_16783.jpg']

## FT

In [17]:
other_data = ["No_sneakers/" + filename for filename in os.listdir("/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers")]
len(other_data)

199

In [18]:
import random
indices = list(range(len(other_data)))
random.seed(42)
random.shuffle(indices)

train_data_other = [other_data[i] for i in indices[:-100]]
test_data_other = [other_data[i] for i in indices[-100:]]

train_data_sneakers = user_data[:-100].path_to_user_photo.to_list()
test_data = user_data[-100:].path_to_user_photo.to_list()

In [85]:
train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

In [86]:
from torch.utils.data import Dataset, DataLoader

class SneakersDataset(Dataset):
    def __init__(self, paths_sneakers, paths_other, transform=None):
        # кроссовки - 0, не кроссовки - 1 
        self.image_paths = paths_sneakers + paths_other
        self.labels = [0] * len(paths_sneakers) + [1] * len(paths_other)
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        label = self.labels[idx]
        
        # Загружаем картинку и переводим в RGB
        image = Image.open(prefix_path + img_path).convert("RGB")
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

In [87]:
train_dataset = SneakersDataset(train_data_sneakers, train_data_other, transform=train_transforms)
test_dataset = SneakersDataset(test_data, test_data_other, transform=train_transforms)

# 4. Создаем DataLoader (теперь их можно подавать в цикл обучения)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [88]:
criterion = torch.nn.CrossEntropyLoss()
# оптимизируем только параметры классификатора
optimizer = torch.optim.Adam(mobilenet.classifier[3].parameters(), lr=0.001)

mobilenet.to(device)

best_accuracy = 0
ft_accuracy = []

for epoch in range(20):

    mobilenet.train()

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs = mobilenet(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    
    mobilenet.eval()

    correct = 0
    total = 0
    
    with torch.no_grad():
        for inputs, labels in test_loader: 
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = mobilenet(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    val_acc = 100 * correct / total
    print(f'Точность на валидации, {epoch} эпоха: {val_acc}%')

    ft_accuracy.append(val_acc)
    if val_acc>best_accuracy:
        torch.save(mobilenet.state_dict(), '/home/inna/Рабочий стол/SneakerSearch/models/best_mobilenet_sneakers.pth')

Точность на валидации, 0 эпоха: 53.5%
Точность на валидации, 1 эпоха: 56.5%
Точность на валидации, 2 эпоха: 59.0%
Точность на валидации, 3 эпоха: 66.5%
Точность на валидации, 4 эпоха: 69.5%
Точность на валидации, 5 эпоха: 76.5%
Точность на валидации, 6 эпоха: 78.0%
Точность на валидации, 7 эпоха: 82.5%
Точность на валидации, 8 эпоха: 84.5%
Точность на валидации, 9 эпоха: 83.5%
Точность на валидации, 10 эпоха: 83.0%
Точность на валидации, 11 эпоха: 84.5%
Точность на валидации, 12 эпоха: 86.0%
Точность на валидации, 13 эпоха: 88.0%
Точность на валидации, 14 эпоха: 87.0%
Точность на валидации, 15 эпоха: 89.5%
Точность на валидации, 16 эпоха: 84.0%
Точность на валидации, 17 эпоха: 83.5%
Точность на валидации, 18 эпоха: 87.5%
Точность на валидации, 19 эпоха: 88.0%

In [ ]:
state_dict = torch.load('/home/inna/Рабочий стол/SneakerSearch/models/best_mobilenet_sneakers.pth')

mobilenet.load_state_dict(state_dict)
mobilenet.eval()

In [104]:
# студийные кроссовки
NO_SNEAKERS=[]
is_sneakers = 0
no_sneakers = 0
for idx, row in lamoda_data[:100].iterrows():
    img_path = prefix_path+row["title_photo"]
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
    else:
        NO_SNEAKERS.append(img_path)
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  95  no_sneakers:  5

In [105]:
NO_SNEAKERS

['/home/inna/Рабочий стол/SneakerSearch/data/lamoda_photos/Matrix_Sport_Matrix_Sport_Кеды_Iconic_44186_0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/lamoda_photos/Covani_Covani_Кеды__1139_0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/lamoda_photos/Reversal_Reversal_Кроссовки__16465_0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/lamoda_photos/Lacoste_Lacoste_Кроссовки_ELITE_ACTIVE_52450_0.jpg',
 "/home/inna/Рабочий стол/SneakerSearch/data/lamoda_photos/O'STIN_O'STIN_Кроссовки__99508_0.jpg"]

In [106]:
# кроссовки
NO_SNEAKERS=[]
is_sneakers = 0
no_sneakers = 0
for image_path, reference_model in image_reference.items():
    img_path = prefix_path+image_path
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
    else:
        NO_SNEAKERS.append(img_path)
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  96  no_sneakers:  4

In [107]:
NO_SNEAKERS

['/home/inna/Рабочий стол/SneakerSearch/data/user_photos/Cotton_Belt_Cotton_Belt_Кеды_Nc_0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/user_photos/Reebok_Reebok_Кеды_CLUB_C_85_VINTAGE_21128_0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/user_photos/Flower_Mountain_Flower_Mountain_Кроссовки_WAVE_2.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/user_photos/Nike_Nike_Кроссовки_W_ZOOM_FLY_6_0.jpg']

In [103]:
# все не кроссовки

IS_SNEAKERS=[]
is_sneakers = 0
no_sneakers = 0
for file in os.listdir("/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers"):
    img_path = prefix_path+"No_sneakers/"+file
    sneakers_proba = sneakers_classifier(img_path)
    if sneakers_proba >= 0.4:
        is_sneakers += 1
        IS_SNEAKERS.append(img_path)
    else:
        no_sneakers += 1
print("is_sneakers: ", is_sneakers, " no_sneakers: ", no_sneakers)

is_sneakers:  29  no_sneakers:  170

In [263]:
IS_SNEAKERS

['/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/nogi_9764.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/7957394408.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/92045f734fa8ec5e3d076ba6cd6054a0.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/Ue929f670f945415490bdc1f65c8c3c15D.jpg_960x960.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo-2023-09-14-19-57-46.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/opening-box-new-leather-boots-person-cardboard-shoe-inside-concept-shopping-footwear-purchase-retail-packaging-444795069.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/9eb967890cd2e56df6dfa33429418f0d.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/8702180870.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/11.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/ab09d6880e330d8291d7f149e29b6484e342807e_1024_1024.jpeg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_basketball2.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/deti_oruzhie_maska_24665.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_led_alpinism_26720.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/f3ZHjstTZXionvsEF0r0FO_XGu9GzrLG3REtoyV3s4rKIzze7_Dr6-iHPQWeyCGzXIx2o_zypi8lARJhaqTYsvo6.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/images.jpeg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/-rJ6OGEr_mo.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/cvety_eda_tarelki_vilka_32888.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/sport_snowboard_24802.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/41599-9397192e.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/8086_320.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/42ae9e2645e320a20f25057ff879a82e.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/AQAFX7qNG7sbcIMHppnj9S5GEBZy-qCw-e3MDeMRhpkjl92Zz62-4avB1PVnjobGQwJn73EMseCejIFvvuP1AMvIDIk.jpg',
 '/home/inna/Рабочий стол/SneakerSearch/data/No_sneakers/photo-2021-11-16-08-15-282.jpg']

## FT CLIP

In [17]:
from collections import defaultdict

lamoda = defaultdict(list)
for idx, row in lamoda_data_racurses.iterrows():
    lamoda[f'{row["model"]}_{row["color"]}'].append(row["title_photo"])
print("Студийных фото ", len(lamoda))

user = defaultdict(list)
for idx, row in user_data.iterrows():
    user[f'{row["model"]}_{row["color"]}'].append(row["path_to_user_photo"])
print("Пользовательских фото ", len(user))

Студийных фото  379
Пользовательских фото  185

In [ ]:
from datasets import Dataset
from sentence_transformers import SentenceTransformer, losses, SentenceTransformerTrainer, SentenceTransformerTrainingArguments


common_models = set(lamoda.keys()).intersection(set(user.keys()))

pairs = []
for model_id in common_models:
    for user_photo in user[f"{model_id}"]:
        lamoda_photo = random.choice(lamoda[f"{model_id}"])
        pairs.append((user_photo, lamoda_photo))

# 1. Подготовка данных в формате словаря (только пути!)
train_data_dict = {
    "image_1": [prefix_path + p[0] for p in pairs],
    "image_2": [prefix_path + p[1] for p in pairs]
}
hf_dataset = Dataset.from_dict(train_data_dict)

model = SentenceTransformer('clip-ViT-B-32', device=device)
train_loss = losses.MultipleNegativesRankingLoss(model)

# 2. Настройка аргументов обучения
args = SentenceTransformerTrainingArguments(
 output_dir='/home/inna/Рабочий стол/SneakerSearch/models/ft_clip_sneakers',
    num_train_epochs=5,          
    per_device_train_batch_size=16, # Уменьшим батч для стабильности
    warmup_steps=20,
    fp16=True,
    save_steps=100,
    logging_steps=10,
    dataloader_num_workers=0,      
    group_by_length=False,        
    report_to="none"  
)

# 3. Создание тренера
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=hf_dataset,
    loss=train_loss,
)

# 4. Запуск (теперь система не должна виснуть)
trainer.train()

/tmp/ipykernel_763905/87939775.py:2: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, losses, SentenceTransformerTrainer, SentenceTransformerTrainingArguments
Loading weights: 100%|██████████| 398/398 [00:00<00:00, 4643.29it/s]
CLIPModel LOAD REPORT from: sentence-transformers/clip-ViT-B-32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
text_model.embeddings.position_ids   | UNEXPECTED |  |
vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:




# # class ImagePairDataset(Dataset):
# #     def __init__(self, pairs, prefix_path):
# #         self.pairs = pairs
# #         self.prefix_path = prefix_path

# #     def __len__(self):
# #         return len(self.pairs)

# #     def __getitem__(self, idx):
# #         user_path, studio_path = self.pairs[idx]
# #         # Открываем картинки только СЕЙЧАС (on-demand)
# #         img1 = Image.open(self.prefix_path + user_path).convert('RGB')
# #         img2 = Image.open(self.prefix_path + studio_path).convert('RGB')
# #         return InputExample(texts=[img1, img2])

# common_models = set(lamoda.keys()).intersection(set(user.keys()))

# # pairs = []
# # for model_id in common_models:
# #     for user_photo in user[f"{model_id}"]:
# #         lamoda_photo = random.choice(lamoda[f"{model_id}"])
# #         pairs.append((user_photo, lamoda_photo))

# # train_dataset = ImagePairDataset(pairs, prefix_path)
# # train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=32, num_workers=4)

# train_examples = []

# # Сопоставляем каждое пользовательское фото со студийным фото этой же модели
# for model_id in common_models:
#     for user_photo in user[f"{model_id}"]:
#         random_idx = random.randint(0, len(lamoda[f"{model_id}"])-1)
#         lamoda_photo = lamoda[f"{model_id}"][random_idx]
#         # Создаем пару положительных примеров
#         train_examples.append(InputExample(texts=[
#             Image.open(prefix_path + user_photo), 
#             Image.open(prefix_path + lamoda_photo)
#         ]))

# train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)

In [22]:
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import Dataset, DataLoader

common_models = set(lamoda.keys()).intersection(set(user.keys()))

train_examples = []
for model_id in common_models:
    for user_photo in user[model_id]:
        studio_photo = random.choice(lamoda[model_id])
      
        train_examples.append(InputExample(texts=[
            prefix_path + user_photo, 
            prefix_path + studio_photo
        ]))

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)

/tmp/ipykernel_747389/3660221959.py:1: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, InputExample, losses

In [ ]:
train_loss = losses.MultipleNegativesRankingLoss(model)

model = SentenceTransformer('clip-ViT-B-32', device=device)

model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=10, 
    warmup_steps=20,
    output_path='/home/inna/Рабочий стол/SneakerSearch/models/ft_clip_sneakers'
)

Loading weights: 100%|██████████| 398/398 [00:00<00:00, 4187.37it/s]
CLIPModel LOAD REPORT from: sentence-transformers/clip-ViT-B-32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
text_model.embeddings.position_ids   | UNEXPECTED |  |
vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
def get_image_embedding(img_path):

    image = Image.open(img_path).convert('RGB')

    with torch.no_grad():
        image_emb = model.encode(
            image,
            convert_to_tensor=True,
            normalize_embeddings=True
            )
    
    return image_emb.cpu().numpy().flatten()

In [ ]:
collection_name = "Sneakers_CLIP_FT"
emb_dim = 512

create_db(
    client,
    collection_name,
    emb_dim,
    lamoda_data
)

In [ ]:
recall_10_clip_ft, recall_5_clip_ft, accuracy_clip_ft, avg_query_time_clip_ft = count_metrics(collection_name)

pd.DataFrame(
    data={
        "CLIP-ViT" : [accuracy_clip, recall_5_clip, recall_10_clip, avg_query_time_clip, 11.3],
        "DINOv2": [accuracy_dino, recall_5_dino, recall_10_dino, avg_query_time_dino, 19.3],
        "CLIP_multivector" : [accuracy_clip_multivectors, recall_5_clip_multivectors, recall_10_clip_multivectors,avg_query_time_clip_multivectors, 264.3],
        "DINO_multivector": [accuracy_dino_multivectors, recall_5_dino_multivectors, recall_10_dino_multivectors, avg_query_time_dino_multivectors, 468.6],
        "CLIP_Milvus_IVF" : [accuracy_clip_ivf, recall_5_clip_ivf, recall_10_clip_ivf, avg_query_time_clip_ivf, 11.6],
        "DINO_Milvus_IVF" : [accuracy_dino_ivf, recall_5_dino_ivf, recall_10_dino_ivf, avg_query_time_dino_ivf, 53],
        "CLIP_FT" : [accuracy_clip_ft, recall_5_clip_ft, recall_10_clip_ft, avg_query_time_clip_ft, ]
    },
    index = ["Accuracy", "Recall@5", "Recall@10", "Avg_query_time, s", "Create_DB_time, s"]
)